### ISSUE TITLE
Pgn4web - Accessibilité - Accessibility

### ISSUE THREAD

**Issue by Alain-Ambazac** [galuel/DiagonaleTV-applets#1]
**Les pages web construites par Pgn4web ne sont actuellement pas accessibles pour les joueurs d’échecs aveugles. Est-il possible de faire des modifications dans ce programme pour que les pages web générées par cette interface le deviennent ?**

Les aveugles se connectent au web avec des lecteurs d’écran.
Sur PC il y a :
- **Jaws for Windows** (Freedom Scientific)
- **NVDA**  (logiciel libre)
  
  **Voice Over**  est le lecteur d’écran pour le Iphone et Mac.

Des tests ont été faits dans l’environnement Windows par plusieurs joueurs d’échecs aveugles utilisant la dernière version de Firefox, avec Jaws et NVDA.
Aucun d’eux n’a pu lire et utiliser les fonctionnalités des pages web créées par Pgn4web.

Problèmes rencontrés :

1 - Le focus n’est pas sur le dernier coup joué. Impossible donc de naviguer avec les flèches de déplacement dans la partie. Le joueur aveugle, en arrivant sur la page web ne sait pas où il se trouve. Il devrait être à l'ouverture de la page positionné automatiquement sur le dernier coup joué. 

2 - Les fenêtres popup comme Shift-d qui leur permettraient de connaitre la position FEN (les diagrammes sont inaccessibles aux aveugles) ont un problème de focus "absent"

3 - Pour une bonne ergonomie, il faudrait ensuite créer 2 raccourci pour permettant d'avancer et de reculer d'un coup blanc. Le joueur aveugle pourrait ainsi se positionner plus rapidement dans la partie qu'il suit avec la lecture immédiate du numéro de coup

Ces modifications, seront non seulement utiles pour eux pour suivre le prochain Championnat de France d'Agens, mais ouvriront la voie à autres sites et blogs dans lesquels Pgn4web est en fonctionnement.

Merci

_**Jaws for Windows peut être téléchargé gratuitement et être utilisé par sessions de 40 minutes.
NVDA est un logiciel libre et son utilisation est gratuite.**_

**Comment by galuel** [comment]
Ok merci, c'est noté. Il y aura une évolution bientôt, et il faudra utiliser la même méthode pour effectuer des retours, en postant sur ce même fil.

**Comment by galuel** [comment]
Création de l'applet live-malvoyants.html, incluant ces fonctionnalités + un menu explicatif.
- Le focus est bien sur le dernier coup joué
- Début de la partie : flèche haute
- Fin de la partie : flèche basse
- Reculer d'un demi-coup : flèche gauche
- Avancer d'un demi-coup : flèche droite
  -La position FEN est sous l'échiquier
