### ISSUE TITLE
Accessibilité - Cahier des charges

### ISSUE THREAD

**Issue by Alain-Ambazac** [galuel/DiagonaleTV-applets#2]
1- Ce qu'il faudrait supprimer de la page: http://www.diagonaletv.com/applets/live-malvoyants.html
- Début de la partie : flèche haute
- Fin de la partie : flèche basse
- Reculer d'un demi-coup : flèche gauche
- Avancer d'un demi-coup : flèche droite
- La position FEN est sous l'échiquier
- FEN:
  Au dessus de l'échiquier et de la partie, indiquer en titre comme dans la version normale la compétition en train d'être suivie avec les mêmes logos de sponsors

2- Créer les 4 liens (positionnement en ligne)
FEN Résultat Pgn-partie Pgn-ronde
Ces 2 dernières entrées sont pour le téléchargement de la partie courante en pgn, et des parties de la ronde en pgn.

3- Formater les intitulés de chaque camp en faisant précéder le nom de chaque joueur par son temps restant et en indiquant la couleur comme ici:
Blancs 0:20:26 - **Navrotescu, Andreea  2275**
Noirs 0:26:41 - **GMf  Maisuradze, Nino  2292**

4 - Positionnement des ancres:
- FEN sur le premier caractère de la position.
- Résultat sur le premier 0 ou 1 des blancs 

5 - Introduire un bip à chaque coup joué. je vous mets le bip choisi en pièce jointe du courrier que je vous envoie ce jour. (coup joué.wav)

6 - Enlever dans les pgn à télécharger les indications de temps

7 - (ultérieurement) résoudre l'impossibilité d'acceder aux raccourcis clavier quand on utilise un lecteur d'écran

8 - (ultérieurement) Pensez-vous qu'il est possible d'interfacer Winboard https://sourceforge.net/projects/winboard45forja/ avec la page du direct ?

**Comment by Alain-Ambazac** [comment]
**Pour ce qui est des liens permettant un téléchargement:**
Ne pas omettre de les faire débuter par "Télécharger". Ce qui devient:
FEN Résultat Télécharger Pgn-partie Télécharger Pgn-ronde
Soit ces liens seront mis le plus en haut dans la page à la façon d'un menu, soit il faudrait les mettre en premier dans l'ordre de tabulation quand on arrive sur la page.

Problème des raccourcis-clavier dont l'absence complique l'usage. 
_Je redis mon impossibilité d'atteindre, via une commande unique, le dernier coup de la partie en cours d'affichage, la manière la plus rapide que j'aie trouvée étant d’aller au séparateur qui suit la partie, (en pressant S avec NVDA) puis de remonter au lien qui précède immédiatement (Maj + K avec NVDA) ; ce n'est pas extrêmement compliqué mais ça manque d'élégance._ (Michel)

**Comment by galuel** [comment]
Voici une nouvelle version de l'applet avec les modifications citées : http://www.diagonaletv.com/applets/live-malvoyants.html

La tester exhaustivement et vérifier qu'elle correspond bien aux fonctionnalités demandées. En cas de nouveau retour, procéder de même dans ce fil.

**Comment by Alain-Ambazac** [comment]
- Les ancres doivent être positionnées en début du texte à lire. Ici elles sont positionnées à la fin.
- Il y a trop d'espace vide vertical, ce qui ne fait pas tenir le contenu sur un écran. 
  _Blancs - 0:26:41 - GMf  Maisuradze, Nino  2292 se trouve rejeté dans le bas  à l'exterieur de l'écran_
  Suggestion coller au maximum le "menu" à la position FEN
- FEN: peut disparaître puisqu'il existe un lien pour s'y rendre direct
- Les pgn contiennent les indications de temps ce qui les rend impropre à la lecture.
  MERCI

**Comment by galuel** [comment]
Concernant les indications de temps, c'est absolument standard et ce ne sera pas changé parce que c'est standard et c'est généré ainsi par les outils DGT.

Si vous n'arrivez pas à lire le PGN standard, c'est le logiciel que vous utilisez qui n'est pas correct, c'est à lui de s'adapter au standard et pas l'inverse.

Je ne comprends pas la phrase : 

"Les ancres doivent être positionnées en début du texte à lire. Ici elles sont positionnées à la fin."

Qui pour moi n'a aucun sens. Il faut préciser ce point.

**Comment by Alain-Ambazac** [comment]
**Pour les ancres,** le curseur qui est visible se trouve positionné actuellement à la fin de la chaîne de caractères. La synthèse de parole lit les chaînes de texte de la gauche vers la droite. Le positionnement du curseur au début d la chaîne de texte évite à l'utilisateur d'avoir à se positionner préalablement en début du texte pour le lire.
**Pour les pgn** Je ne doute pas que le pgn fourni soit standard et normalisé. Cependant, il ne correspond pas dans cette forme au standard de distribution en direction des utilisateurs. Ouvrez par exemple avec le bloc-note Windows ou un simple éditeur de textes les pgn proposés par le site d'échecs et entre-autres the week in chess http://theweekinchess.com/
exemple:  http://www.theweekinchess.com/zips/twic1129g.zip

**Comment by galuel** [comment]
Ce n'est pas the week in chess qui définit le standard des PGN :) Ca ne sera pas changé. Il vous faut trouver les logiciels qui feront le travail de lecture correct (ou de transformation correct), ce n'est pas de l'ordre des applets proposées que de toucher quoi que ce soit au standard.

Je crois avec compris pour le curseur, je verrai ça.

**Comment by galuel** [comment]
Nouvelle version avec le focus systématiquement en début + le son a été rajouté lors du changement de tout coup :  http://www.diagonaletv.com/applets/live-malvoyants.html

Pourquoi pas ce son, mais je le trouve un peu agressif, n'y-a-t-il pas d'autres fichiers sons ? Il faudrait demander aux testeurs ce qu'ils veulent comme son, je peux rajouter facilement une option pour choisir le fichier son que l'on veut parmi une liste, il faudra juste me donner les fichiers wav.

**Comment by Alain-Ambazac** [comment]
Cette option pour le son, ça va être très bien. Certains aveugles on l’ouïe fine mais d'autres ont du mal à entendre. Le réglage du niveau c'est top!. 
Je leur envoie ça ce soir et on laisse décanter un peu.
Merci beaucoup.

**Comment by Alain-Ambazac** [comment]
Au rafraîchissement de la page, le volume pourrait-il conserver son réglage de niveau?

**Comment by Alain-Ambazac** [comment]
Vous avez peut-être d'autres players? Je devance ici les réactions... Il ne semble réglable qu'à la souris.
Si vous n'avez rien d'autre, on fera avec. Ne vous prenez pas la tête.
Dans des trucs bien foutus, il y a un menu contextuel qui permet d'effectuer tous les réglages au clavier.

**Comment by galuel** [comment]
Il faut distinguer en informatique ce qui est la mise au point des fonctionnalités de base, avec ce qui est optimisation de confort. Dans un premier temps on s'assure que l'ensemble des fonctionnalités de base sont présentes et fonctionnelles, puis dans un deuxième temps on envisage de faire des optomisations de confort.

Prenez le temps avec d'autres testeurs de bien faire le tour de cette nouvelle version, les fonctionnalités de base étant là, on fera une clôture de ce fil. S'il y a des bugs constatés plus tard à l'utilisation il faudra le signaler en ouvrant une nouvelle issue. Puis s'il y a des améliorations possibles, de la même façon les utilisateurs pourront ouvrir une autre issue.

C'est la méthode à employer pour accompagner le développement d'un logiciel.

**Comment by galuel** [comment]
Done in 0.90 version sous live-accessibilite.html
