### ISSUE TITLE
réglage du niveau du son

### ISSUE THREAD

**Issue by Alain-Ambazac** [galuel/DiagonaleTV-applets#3]
Le fichier audio initial click2.wav est OK.
Le niveau est trop important. Pourriez-vous baisser son niveau de moitié?
Merci

**Comment by galuel** [comment]
Résolu, le niveau par défaut a été mis à 50%

La page disponible a été changée de nom pour live-accessibilite.html, l'ancienne page a été supprimée. Il faut désormais vérifier et tester ici : http://www.diagonaletv.com/applets/live-accessibilite.html

C'est comme cela qu'il faut procéder, un seul bug, ou modification souhaitée = 1 seule issue, faire autant d'issues que de demandes précises et ne pas les regrouper toutes dans la même issue. Cela permet de sérialiser le développement.

**Comment by Alain-Ambazac** [comment]
Merci Stéphane, j'ai compris.
